/* DiskLens - frontend */

const $ = (id) => document.getElementById(id);
const TOKEN = document.querySelector('meta[name="disklens-token"]').content;

const state = {
  results: null,
  info: null,
  selection: new Map(), // path -> { size, contentsOnly }
};

/* ------------------------------------------------------------------- i18n */

const I18N = {
  en: {
    "admin.yes": "administrator mode",
    "admin.no": "not administrator, some folders stay hidden",
    "ph.path": "C:\\",
    "ph.filter": "filter path",
    "ctl.mindup": "min duplicate",
    "ctl.scan": "Scan",
    "ctl.cancel": "Cancel",
    "ctl.emptybin": "Empty Recycle Bin",
    "welcome.title": "See what is eating your disk",
    "welcome.sub": "DiskLens maps your drive, finds the biggest folders and files, detects real duplicates by content, and measures the caches your system can safely rebuild.",
    "welcome.s1t": "Pick a drive",
    "welcome.s1": "Choose the drive that is full and press Scan. A full drive takes 3 to 15 minutes.",
    "welcome.s2t": "Read the diagnosis",
    "welcome.s2": "DiskLens shows where the space went and how much you can get back.",
    "welcome.s3t": "Select and delete",
    "welcome.s3": "Nothing is deleted unless you tick it and confirm. Deleted items go to the Recycle Bin.",
    "welcome.admin": "Tip: run as administrator to see system folders that are otherwise hidden from the scan.",
    "band.freein": "Free space on",
    "band.free": "free",
    "band.total": "Total",
    "band.used": "Used",
    "band.reclaim": "Reclaimable",
    "tab.diag": "Diagnosis",
    "tab.clean": "Quick cleanup",
    "tab.dirs": "Folders",
    "tab.files": "Files",
    "tab.dups": "Duplicates",
    "tab.old": "Old files",
    "diag.where": "Where the space went",
    "diag.level1": "Top level folders",
    "diag.byext": "By file type",
    "clean.known": "Known cleanup targets",
    "clean.project": "Build and dependency folders",
    "clean.projectnote": "Folders generated by package managers and build tools. One command in the project recreates them.",
    "clean.empty": "No known cleanup target found with a relevant size.",
    "clean.projectempty": "No node_modules, __pycache__, .venv or build folder found.",
    "dirs.all": "All levels",
    "dirs.l1": "Level 1",
    "dirs.l2": "Level 2",
    "dirs.l3": "Level 3",
    "dirs.empty": "No folder matches the filter.",
    "files.empty": "No file matches the filter.",
    "files.modified": "modified on",
    "files.lastmod": "last modified on",
    "dups.selectextra": "Select every extra copy",
    "dups.note": "Files are matched by content hash, not by name. The first copy of each group is kept and cannot be selected.",
    "dups.empty": "No duplicate above the minimum size. Lower the min duplicate value and scan again to look for smaller files.",
    "dups.summary": "{n} groups, {size} wasted on extra copies.",
    "dups.copies": "{n} copies",
    "dups.each": "{size} each",
    "dups.match": "match",
    "dups.exact": "exact",
    "dups.partial": "sampled",
    "dups.waste": "waste",
    "dups.keep": "keep",
    "old.note": "Files above 100 MB that have not been modified for more than a year.",
    "old.empty": "No large old file found.",
    "bar.selected": "selected",
    "bar.clear": "Clear selection",
    "bar.trash": "Move to Recycle Bin",
    "bar.perm": "Delete permanently",
    "bar.permoff": "Permanent delete is disabled. Restart with --allow-permanent to enable it.",
    "modal.back": "Back",
    "modal.confirm": "Confirm",
    "modal.trashtitle": "Move to Recycle Bin",
    "modal.permtitle": "Delete permanently",
    "modal.trashtext": "<b>{n}</b> items, <b>{size}</b>. They go to the Recycle Bin and can be restored. Space is only freed once the bin is emptied.",
    "modal.permtext": "<b>{n}</b> items, <b>{size}</b>. This cannot be undone. Space is freed immediately.",
    "modal.contents": "(contents only, folder is kept)",
    "legend.risk": "<b class='ok'>Safe</b> is rebuilt automatically. <b class='warn'>Careful</b> is rebuilt too, but costs time or a download. <b class='info'>Info</b> cannot be deleted here and shows the command to use.",
    "risk.safe": "safe",
    "risk.careful": "careful",
    "risk.info": "info",
    "status.scanning": "Scanning files",
    "status.hashing": "Comparing files",
    "status.aggregating": "Aggregating folders",
    "status.measuring": "Measuring cleanup targets",
    "stats.line": "{files} files · {size} · {dirs} folders · {sec}s",
    "toast.done": "Scan complete. Estimated reclaimable: <b>{size}</b>",
    "toast.cancelled": "Scan cancelled.",
    "toast.error": "Scan error: {msg}",
    "toast.freed": "Freed <b>{size}</b> across {n} items.",
    "toast.failed": "{n} items were not removed: {list}",
    "toast.binempty": "Recycle Bin emptied.",
    "toast.binerror": "Could not empty the Recycle Bin: {msg}",
    "toast.trashnote": "Remember: the space is only freed when you empty the Recycle Bin.",
    "verdict.situation": "Situation",
    "verdict.free": "{pct}% free",
    "verdict.critical": "Critical. Below 5 percent Windows becomes unstable and updates fail.",
    "verdict.tight": "Tight. Below 10 percent updates and virtual memory start to suffer.",
    "verdict.fine": "Comfortable for now.",
    "verdict.quickwin": "Quick win",
    "verdict.quickwintext": "Safe cleanup ({safe}), duplicates ({dup}) and build folders ({proj}) added together.",
    "verdict.unaccounted": "Not seen by the scan",
    "verdict.unaccountedbig": "This is usually the paging file, hibernation file, restore points or folders the scan could not read. Run as administrator and check the Quick cleanup tab.",
    "verdict.unaccountedsmall": "Normal gap between what the system reserves and what a file scan can see.",
    "verdict.analyzed": "Files analysed",
    "verdict.analyzedtext": "{dirs} folders, {errors} could not be read.",
    "verdict.biggestdir": "Largest concentration",
    "verdict.biggestfile": "Largest file",
    "err.not_found": "no longer exists",
    "err.protected": "protected system folder",
    "err.too_shallow": "path is too close to the drive root",
    "err.inside_windows": "inside the Windows folder, outside the safe list",
    "err.installed_program": "installed program, uninstall it instead",
    "err.system_file": "system file, use the command shown in the interface",
    "err.permanent_disabled": "permanent delete is disabled",
    "err.empty_path": "empty path",
    "err.invalid_path": "invalid path",
    "err.scan_running": "a scan is already running",
    "help.title": "How DiskLens works",
    "help.close": "Got it",
    "files.dblclick": "double click opens the folder",
    "lang.other": "PT",
  },
  pt: {
    "admin.yes": "modo administrador",
    "admin.no": "sem admin, algumas pastas ficam ocultas",
    "ph.path": "C:\\",
    "ph.filter": "filtrar caminho",
    "ctl.mindup": "duplicado mín",
    "ctl.scan": "Analisar",
    "ctl.cancel": "Cancelar",
    "ctl.emptybin": "Esvaziar lixeira",
    "welcome.title": "Veja o que está ocupando seu disco",
    "welcome.sub": "O DiskLens mapeia sua unidade, encontra as maiores pastas e arquivos, detecta duplicados de verdade pelo conteúdo e mede os caches que o sistema recria sozinho.",
    "welcome.s1t": "Escolha a unidade",
    "welcome.s1": "Selecione o disco que está cheio e clique em Analisar. Um disco cheio leva de 3 a 15 minutos.",
    "welcome.s2t": "Leia o diagnóstico",
    "welcome.s2": "O DiskLens mostra para onde o espaço foi e quanto dá para recuperar.",
    "welcome.s3t": "Selecione e apague",
    "welcome.s3": "Nada é apagado sem você marcar e confirmar. O padrão é enviar para a lixeira.",
    "welcome.admin": "Dica: rode como administrador para enxergar pastas de sistema que ficam invisíveis para a varredura.",
    "band.freein": "Espaço livre em",
    "band.free": "livre",
    "band.total": "Total",
    "band.used": "Usado",
    "band.reclaim": "Recuperável",
    "tab.diag": "Diagnóstico",
    "tab.clean": "Limpeza rápida",
    "tab.dirs": "Pastas",
    "tab.files": "Arquivos",
    "tab.dups": "Duplicados",
    "tab.old": "Antigos",
    "diag.where": "Onde o espaço está",
    "diag.level1": "Pastas de primeiro nível",
    "diag.byext": "Por tipo de arquivo",
    "clean.known": "Lixo conhecido",
    "clean.project": "Pastas de build e dependências",
    "clean.projectnote": "Pastas geradas por gerenciadores de pacote e ferramentas de build. Um comando no projeto recria todas.",
    "clean.empty": "Nenhuma pasta de lixo conhecida encontrada com tamanho relevante.",
    "clean.projectempty": "Nenhuma pasta node_modules, __pycache__, .venv ou build encontrada.",
    "dirs.all": "Todos os níveis",
    "dirs.l1": "Nível 1",
    "dirs.l2": "Nível 2",
    "dirs.l3": "Nível 3",
    "dirs.empty": "Nenhuma pasta corresponde ao filtro.",
    "files.empty": "Nenhum arquivo corresponde ao filtro.",
    "files.modified": "modificado em",
    "files.lastmod": "última modificação em",
    "dups.selectextra": "Marcar todas as cópias extras",
    "dups.note": "Os arquivos são comparados por hash do conteúdo, não pelo nome. A primeira cópia de cada grupo é mantida e não pode ser marcada.",
    "dups.empty": "Nenhum duplicado acima do tamanho mínimo. Reduza o valor de duplicado mín e analise de novo para procurar arquivos menores.",
    "dups.summary": "{n} grupos, {size} desperdiçados em cópias extras.",
    "dups.copies": "{n} cópias",
    "dups.each": "{size} cada",
    "dups.match": "correspondência",
    "dups.exact": "exata",
    "dups.partial": "por amostragem",
    "dups.waste": "desperdício",
    "dups.keep": "manter",
    "old.note": "Arquivos acima de 100 MB sem modificação há mais de um ano.",
    "old.empty": "Nenhum arquivo grande e antigo encontrado.",
    "bar.selected": "itens selecionados",
    "bar.clear": "Limpar seleção",
    "bar.trash": "Enviar para a lixeira",
    "bar.perm": "Apagar definitivamente",
    "bar.permoff": "Exclusão permanente desativada. Reinicie com --allow-permanent para habilitar.",
    "modal.back": "Voltar",
    "modal.confirm": "Confirmar",
    "modal.trashtitle": "Enviar para a lixeira",
    "modal.permtitle": "Apagar definitivamente",
    "modal.trashtext": "<b>{n}</b> itens, <b>{size}</b>. Vão para a lixeira e podem ser restaurados. O espaço só é liberado quando a lixeira for esvaziada.",
    "modal.permtext": "<b>{n}</b> itens, <b>{size}</b>. Não tem volta. O espaço é liberado na hora.",
    "modal.contents": "(apenas o conteúdo, a pasta é mantida)",
    "legend.risk": "<b class='ok'>Seguro</b> volta a ser criado sozinho. <b class='warn'>Cuidado</b> também é recriável, mas custa tempo ou download. <b class='info'>Info</b> não pode ser apagado aqui e mostra o comando correto.",
    "risk.safe": "seguro",
    "risk.careful": "cuidado",
    "risk.info": "info",
    "status.scanning": "Varrendo arquivos",
    "status.hashing": "Comparando arquivos",
    "status.aggregating": "Agregando pastas",
    "status.measuring": "Medindo alvos de limpeza",
    "stats.line": "{files} arquivos · {size} · {dirs} pastas · {sec}s",
    "toast.done": "Análise concluída. Recuperável estimado: <b>{size}</b>",
    "toast.cancelled": "Análise cancelada.",
    "toast.error": "Erro na análise: {msg}",
    "toast.freed": "Liberado <b>{size}</b> em {n} itens.",
    "toast.failed": "{n} itens não removidos: {list}",
    "toast.binempty": "Lixeira esvaziada.",
    "toast.binerror": "Não foi possível esvaziar a lixeira: {msg}",
    "toast.trashnote": "Lembre-se: o espaço só é liberado quando você esvaziar a lixeira.",
    "verdict.situation": "Situação",
    "verdict.free": "{pct}% livre",
    "verdict.critical": "Crítico. Abaixo de 5 por cento o Windows fica instável e atualizações falham.",
    "verdict.tight": "Apertado. Abaixo de 10 por cento já atrapalha updates e memória virtual.",
    "verdict.fine": "Confortável por enquanto.",
    "verdict.quickwin": "Ganho rápido",
    "verdict.quickwintext": "Somando lixo seguro ({safe}), duplicados ({dup}) e pastas de build ({proj}).",
    "verdict.unaccounted": "Não visto pela varredura",
    "verdict.unaccountedbig": "Isso costuma ser arquivo de paginação, hibernação, pontos de restauração ou pastas sem permissão de leitura. Rode como administrador e veja a aba Limpeza rápida.",
    "verdict.unaccountedsmall": "Diferença normal entre o que o sistema reserva e o que uma varredura de arquivos enxerga.",
    "verdict.analyzed": "Arquivos analisados",
    "verdict.analyzedtext": "{dirs} pastas, {errors} sem permissão de leitura.",
    "verdict.biggestdir": "Maior concentração",
    "verdict.biggestfile": "Maior arquivo",
    "err.not_found": "não existe mais",
    "err.protected": "pasta protegida do sistema",
    "err.too_shallow": "caminho perto demais da raiz do disco",
    "err.inside_windows": "dentro da pasta Windows, fora da lista segura",
    "err.installed_program": "programa instalado, desinstale pelo painel",
    "err.system_file": "arquivo de sistema, use o comando indicado",
    "err.permanent_disabled": "exclusão permanente desativada",
    "err.empty_path": "caminho vazio",
    "err.invalid_path": "caminho inválido",
    "err.scan_running": "já existe uma análise em andamento",
    "help.title": "Como o DiskLens funciona",
    "help.close": "Entendi",
    "files.dblclick": "duplo clique abre a pasta",
    "lang.other": "EN",
  },
};

/* Cleanup target names and notes come from the backend in English.
   This table translates them for the Portuguese interface. */
const JUNK_PT = {
  user_temp: ["Temporários do usuário", "Arquivos temporários de programas e instaladores. Recriados automaticamente."],
  windows_temp: ["Temporários do Windows", "Temporários do sistema. Precisa de administrador para limpar tudo."],
  windows_update_cache: ["Cache do Windows Update", "Instaladores de atualizações já aplicadas. Costuma ter vários GB."],
  delivery_optimization: ["Cache do Delivery Optimization", "Cache ponto a ponto usado para compartilhar atualizações."],
  wer_user: ["Relatórios de erro (usuário)", "Relatórios de travamento de programas."],
  wer_system: ["Relatórios de erro (sistema)", "Relatórios de travamento coletados pelo sistema."],
  crash_dumps: ["Despejos de memória", "Dumps de programas que travaram."],
  thumbnail_cache: ["Cache de miniaturas e ícones", "Miniaturas do Explorer. Recriadas ao navegar nas pastas."],
  inetcache: ["Cache de internet", "Cache usado pelo sistema e por navegadores embutidos."],
  prefetch: ["Prefetch", "Acelera a abertura de programas. Limpar deixa o boot lento por alguns dias."],
  windows_old: ["Instalação anterior do Windows", "Windows antigo, normalmente de 10 a 30 GB. Apagar remove a opção de voltar."],
  chrome_cache: ["Cache do Chrome", "Cache de páginas. Recriado ao navegar."],
  edge_cache: ["Cache do Edge", "Cache de páginas. Recriado ao navegar."],
  brave_cache: ["Cache do Brave", "Cache de páginas. Recriado ao navegar."],
  firefox_cache: ["Cache do Firefox", "Cache de páginas. Recriado ao navegar."],
  pip_cache: ["Cache do pip", "Pacotes Python baixados. Recriado no próximo pip install."],
  npm_cache: ["Cache do npm", "Pacotes Node baixados. Recriado no próximo npm install."],
  yarn_cache: ["Cache do Yarn", "Pacotes Yarn baixados."],
  vscode_cache: ["Cache do VS Code", "Cache do editor. Recriado ao abrir o VS Code."],
  vscode_cacheddata: ["Dados em cache do VS Code", "Bytecode de versões antigas do editor."],
  nuget_packages: ["Pacotes NuGet", "Pacotes .NET baixados. Recriado no próximo restore, builds offline quebram antes."],
  docker_vhdx: ["Disco do Docker (ext4.vhdx)", "Disco virtual do Docker. Nunca apague. Rode 'docker system prune -a' e depois compacte o vhdx."],
  mt5_logs: ["Logs do MetaTrader", "Logs do terminal e de robôs. Crescem rápido com backtest."],
  mt5_tester: ["Cache do Strategy Tester", "Agentes e caches de otimização. Recriados no próximo backtest."],
  mt5_bases: ["Histórico de preços do MetaTrader", "Ticks e barras baixados do broker. Pode passar de dezenas de GB, rebaixável."],
  nt8_logs: ["Logs do NinjaTrader", "Arquivos diários de log e trace."],
  nt8_db: ["Dados de mercado do NinjaTrader", "Histórico de mercado. Rebaixável pelo Historical Data Manager."],
  spotify_cache: ["Cache do Spotify", "Músicas em cache para ouvir offline."],
  discord_cache: ["Cache do Discord", "Imagens e anexos em cache."],
  teams_cache: ["Cache do Teams", "Cache do Teams clássico. Feche o aplicativo antes."],
  hiberfil: ["hiberfil.sys (hibernação)", "Arquivo de hibernação, cerca de 40 por cento da sua RAM. Desative com: powercfg /h off"],
  pagefile: ["pagefile.sys (memória virtual)", "Arquivo de paginação. Não apague. Redimensione em Propriedades do Sistema, Avançado, Desempenho."],
  swapfile: ["swapfile.sys", "Paginação de aplicativos da Store. Controlado pelo sistema."],
  winsxs: ["WinSxS (componentes do Windows)", "Nunca apague manualmente. Limpe com: DISM /Online /Cleanup-Image /StartComponentCleanup"],
  system_restore: ["Restauração do sistema", "Pontos de restauração podem ocupar 10 por cento do disco. Veja com: vssadmin list shadowstorage"],
  recycle_bin: ["Lixeira", "Arquivos excluídos ainda ocupam espaço. Use o botão Esvaziar lixeira no topo."],
  unix_cache: ["Cache do usuário", "Cache genérico de aplicativos."],
  unix_trash: ["Lixeira", "Arquivos excluídos ainda ocupam espaço."],
};

const PROJECT_KIND = {
  node_deps: ["Node dependencies, recreated by npm install", "Dependências Node, recriadas com npm install"],
  pycache: ["Python bytecode cache, recreated on the next run", "Cache de bytecode Python, recriado na próxima execução"],
  venv: ["Python virtual environment, recreated from requirements", "Ambiente virtual Python, recriado a partir do requirements"],
  next_build: ["Next.js build cache, recreated by the next build", "Cache de build do Next.js, recriado no próximo build"],
  build_output: ["Build output, recreated by the next build", "Saída de build, recriada no próximo build"],
  gradle_cache: ["Gradle cache, re-downloaded when needed", "Cache do Gradle, rebaixado quando necessário"],
  generic_cache: ["Generic tool cache", "Cache genérico de ferramenta"],
};

let LANG = "en";

function t(key, params) {
  let s = (I18N[LANG] && I18N[LANG][key]) || I18N.en[key] || key;
  if (params) {
    Object.keys(params).forEach((k) => { s = s.split("{" + k + "}").join(params[k]); });
  }
  return s;
}

function detectLang() {
  let saved = null;
  try { saved = localStorage.getItem("disklens_lang"); } catch (e) { /* ignore */ }
  if (saved === "pt" || saved === "en") return saved;
  return (navigator.language || "en").toLowerCase().startsWith("pt") ? "pt" : "en";
}

function applyI18n() {
  document.documentElement.lang = LANG === "pt" ? "pt-BR" : "en";
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    el.textContent = t(el.dataset.i18n);
  });
  document.querySelectorAll("[data-i18n-ph]").forEach((el) => {
    el.placeholder = t(el.dataset.i18nPh);
  });
  $("langBtn").textContent = t("lang.other");
  $("riskLegend").innerHTML = t("legend.risk");
  if (state.info) setAdminFlag(state.info.admin);
  if (state.results) render(state.results);
  renderActionBar();
  renderHelp();
}

/* ------------------------------------------------------------------ utils */

function fmt(bytes) {
  const b = Number(bytes) || 0;
  if (b >= 1024 ** 4) return (b / 1024 ** 4).toFixed(2) + " TB";
  if (b >= 1024 ** 3) return (b / 1024 ** 3).toFixed(1) + " GB";
  if (b >= 1024 ** 2) return (b / 1024 ** 2).toFixed(0) + " MB";
  if (b >= 1024) return (b / 1024).toFixed(0) + " KB";
  return b + " B";
}

function num(n) {
  return (Number(n) || 0).toLocaleString(LANG === "pt" ? "pt-BR" : "en-US");
}

function fmtDate(ts) {
  if (!ts) return "";
  return new Date(ts * 1000).toLocaleDateString(LANG === "pt" ? "pt-BR" : "en-US",
    { year: "numeric", month: "2-digit", day: "2-digit" });
}

function esc(s) {
  return String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
}

function errText(code) {
  const key = "err." + code;
  const translated = t(key);
  return translated === key ? code : translated;
}

async function api(route, body) {
  const opts = { headers: { "X-DiskLens-Token": TOKEN } };
  if (body) {
    opts.method = "POST";
    opts.headers["Content-Type"] = "application/json";
    opts.body = JSON.stringify(body);
  }
  const res = await fetch(route, opts);
  return res.json();
}

let toastTimer = null;
function toast(html) {
  const el = $("toast");
  el.innerHTML = html;
  el.hidden = false;
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => { el.hidden = true; }, 7000);
}

function openPath(path) { api("/api/open", { path }); }

/* -------------------------------------------------------------- selection */

function toggleSelect(path, size, contentsOnly, checked) {
  if (checked) state.selection.set(path, { size, contentsOnly: !!contentsOnly });
  else state.selection.delete(path);
  renderActionBar();
}

function renderActionBar() {
  const n = state.selection.size;
  $("actionbar").hidden = n === 0;
  let total = 0;
  state.selection.forEach((v) => { total += v.size || 0; });
  $("selCount").textContent = n;
  $("selSize").textContent = fmt(total);
}

function clearSelection() {
  state.selection.clear();
  document.querySelectorAll("input[type=checkbox][data-path]").forEach((c) => { c.checked = false; });
  document.querySelectorAll(".row.selected").forEach((r) => r.classList.remove("selected"));
  renderActionBar();
}

/* ------------------------------------------------------------------- rows */

function rowHTML(path, size, max, opts = {}) {
  const pct = max > 0 ? Math.max(1, Math.round((size / max) * 100)) : 0;
  const sub = opts.sub ? `<small>${esc(opts.sub)}</small>` : "";
  const box = opts.noCheck
    ? '<span class="dim mono">-</span>'
    : `<input type="checkbox" data-path="${esc(path)}" data-size="${size}" data-contents="${opts.contentsOnly ? 1 : 0}">`;
  return `<div class="row" data-rowpath="${esc(path)}">
      ${box}
      <div class="path" title="${esc(path)} (${t("files.dblclick")})">${esc(opts.label || path)}${opts.badge || ""}${sub}</div>
      <div class="meter"><i style="width:${pct}%"></i></div>
      <div class="size">${fmt(size)}</div>
    </div>`;
}

function bindRows(container) {
  container.querySelectorAll("input[type=checkbox][data-path]").forEach((cb) => {
    cb.addEventListener("change", () => {
      cb.closest(".row").classList.toggle("selected", cb.checked);
      toggleSelect(cb.dataset.path, Number(cb.dataset.size), cb.dataset.contents === "1", cb.checked);
    });
  });
  container.querySelectorAll(".path").forEach((p) => {
    p.addEventListener("dblclick", () => openPath(p.closest(".row").dataset.rowpath));
  });
}

function fillList(el, items, mapper, emptyMsg) {
  if (!items || !items.length) {
    el.innerHTML = `<div class="emptystate">${esc(emptyMsg)}</div>`;
    return;
  }
  const max = Math.max(...items.map((i) => i.size || 0));
  el.innerHTML = items.map((i) => mapper(i, max)).join("");
  bindRows(el);
}

/* ----------------------------------------------------------------- render */

function render(r) {
  state.results = r;
  $("welcome").hidden = true;
  $("app").hidden = false;

  const disk = r.disk || { total: 0, used: 0, free: 0 };
  $("bandRoot").textContent = r.root;
  $("freeVal").textContent = fmt(disk.free);
  $("totalVal").textContent = fmt(disk.total);
  $("usedVal").textContent = fmt(disk.used);

  const p = {
    safe: r.junk_safe_total || 0,
    careful: r.junk_careful_total || 0,
    dup: r.dup_waste || 0,
    proj: r.project_junk_total || 0,
  };
  p.reclaim = p.safe + p.careful + p.dup + p.proj;
  $("reclaimVal").textContent = fmt(p.reclaim);

  renderStack(disk, p);
  renderVerdicts(r, disk, p);
  renderLevel1(r);
  renderExt(r);
  renderJunk(r);
  renderProjectJunk(r);
  renderDirs();
  renderFiles();
  renderDups(r);
  renderOld(r);
}

function renderStack(disk, p) {
  const rest = Math.max(0, disk.used - p.safe - p.careful - p.dup - p.proj);
  const segs = [
    { label: t("risk.safe"), v: p.safe, c: "#4fae6c" },
    { label: t("risk.careful"), v: p.careful, c: "#d98c1f" },
    { label: t("tab.dups"), v: p.dup, c: "#f5a800" },
    { label: t("clean.project"), v: p.proj, c: "#8e6bbf" },
    { label: t("band.used"), v: rest, c: "#3a3a3a" },
    { label: t("band.free"), v: disk.free, c: "#151515" },
  ].filter((s) => s.v > 0);
  const total = disk.total || segs.reduce((a, s) => a + s.v, 0) || 1;
  $("stack").innerHTML = segs
    .map((s) => `<div style="width:${(s.v / total) * 100}%;background:${s.c}" title="${esc(s.label)}: ${fmt(s.v)}"></div>`)
    .join("");
  $("stackLegend").innerHTML = segs
    .map((s) => `<span><i style="background:${s.c}"></i>${esc(s.label)} <b class="mono">${fmt(s.v)}</b></span>`)
    .join("");
}

function renderVerdicts(r, disk, p) {
  const pctFree = disk.total ? (disk.free / disk.total) * 100 : 0;
  const notScanned = Math.max(0, disk.used - (r.root_total || 0));
  const cards = [
    {
      label: t("verdict.situation"),
      kpi: t("verdict.free", { pct: pctFree.toFixed(1) }),
      text: pctFree < 5 ? t("verdict.critical") : pctFree < 10 ? t("verdict.tight") : t("verdict.fine"),
    },
    {
      label: t("verdict.quickwin"),
      kpi: fmt(p.reclaim),
      text: t("verdict.quickwintext", { safe: fmt(p.safe), dup: fmt(p.dup), proj: fmt(p.proj) }),
    },
    {
      label: t("verdict.unaccounted"),
      kpi: fmt(notScanned),
      text: notScanned > 5 * 1024 ** 3 ? t("verdict.unaccountedbig") : t("verdict.unaccountedsmall"),
    },
    {
      label: t("verdict.analyzed"),
      kpi: num(r.files),
      text: t("verdict.analyzedtext", { dirs: num(r.dirs), errors: num(r.errors) }),
    },
  ];

  const topDir = (r.top_dirs || []).find((d) => d.depth >= 1 && d.depth <= 2);
  if (topDir) cards.push({ label: t("verdict.biggestdir"), kpi: fmt(topDir.size), text: topDir.path });
  const topFile = (r.top_files || [])[0];
  if (topFile) cards.push({ label: t("verdict.biggestfile"), kpi: fmt(topFile.size), text: topFile.path });

  $("verdicts").innerHTML = cards
    .map((c) => `<div class="card">
        <div class="label">${esc(c.label)}</div>
        <div class="kpi">${esc(c.kpi)}</div>
        <p>${esc(c.text)}</p>
      </div>`)
    .join("");
}

function junkText(j) {
  if (LANG === "pt" && JUNK_PT[j.id]) return { name: JUNK_PT[j.id][0], note: JUNK_PT[j.id][1] };
  return { name: j.name, note: j.note };
}

function renderLevel1(r) {
  fillList($("level1"), (r.top_dirs || []).filter((d) => d.depth === 1).slice(0, 12),
    (d, max) => rowHTML(d.path, d.size, max, { sub: num(d.files) + " " + t("tab.files").toLowerCase() }),
    t("dirs.empty"));
}

function renderExt(r) {
  const items = (r.by_ext || []).slice(0, 12).map((e) => ({ path: e.ext, size: e.size, files: e.files }));
  fillList($("byExt"), items,
    (e, max) => rowHTML(e.path, e.size, max, { noCheck: true, sub: num(e.files) + " " + t("tab.files").toLowerCase() }),
    t("dirs.empty"));
}

function renderJunk(r) {
  const junk = r.junk || [];
  const real = junk.filter((j) => j.kind !== "info" && j.exists && j.size > 0);
  const info = junk.filter((j) => j.kind === "info");
  const max = Math.max(1, ...real.map((j) => j.size));

  let html = real.map((j) => {
    const txt = junkText(j);
    const badge = `<span class="riskbadge r-${j.risk}">${t("risk." + j.risk)}</span>`;
    return j.resolved.map((res, idx) =>
      rowHTML(res.path, res.size, max, {
        label: idx === 0 ? txt.name : txt.name + " (" + (idx + 1) + ")",
        badge: idx === 0 ? badge : "",
        sub: idx === 0 ? txt.note + "  ·  " + res.path : res.path,
        contentsOnly: j.kind === "contents",
      })).join("");
  }).join("");

  if (!html) html = `<div class="emptystate">${esc(t("clean.empty"))}</div>`;

  html += info.map((j) => {
    const txt = junkText(j);
    const size = j.size ? ` <b class="mono accent">${fmt(j.size)}</b>` : "";
    return `<div class="row" data-rowpath="${esc(j.path || "")}">
        <span class="dim mono">i</span>
        <div class="path">${esc(txt.name)}<span class="riskbadge r-info">${t("risk.info")}</span>${size}
          <small>${esc(txt.note)}</small></div>
        <div class="meter"></div>
        <div class="size">${j.size ? fmt(j.size) : "-"}</div>
      </div>`;
  }).join("");

  $("junkList").innerHTML = html;
  bindRows($("junkList"));
}

function renderProjectJunk(r) {
  fillList($("projectJunk"), r.project_junk || [], (d, max) => {
    const pair = PROJECT_KIND[d.kind] || ["", ""];
    return rowHTML(d.path, d.size, max, { sub: LANG === "pt" ? pair[1] : pair[0] });
  }, t("clean.projectempty"));
}

function renderDirs() {
  const r = state.results;
  const q = $("dirFilter").value.toLowerCase();
  const depth = Number($("dirDepth").value);
  let items = r.top_dirs || [];
  if (q) items = items.filter((d) => d.path.toLowerCase().includes(q));
  if (depth) items = items.filter((d) => d.depth === depth);
  fillList($("dirList"), items.slice(0, 150),
    (d, max) => rowHTML(d.path, d.size, max, { sub: num(d.files) + " " + t("tab.files").toLowerCase() }),
    t("dirs.empty"));
}

function renderFiles() {
  const r = state.results;
  const q = $("fileFilter").value.toLowerCase();
  let items = r.top_files || [];
  if (q) items = items.filter((f) => f.path.toLowerCase().includes(q));
  fillList($("fileList"), items.slice(0, 200),
    (f, max) => rowHTML(f.path, f.size, max, { sub: t("files.modified") + " " + fmtDate(f.mtime) }),
    t("files.empty"));
}

function renderDups(r) {
  const groups = r.duplicates || [];
  $("dupSummary").textContent = groups.length
    ? t("dups.summary", { n: groups.length, size: fmt(r.dup_waste) })
    : "";
  if (!groups.length) {
    $("dupList").innerHTML = `<div class="emptystate">${esc(t("dups.empty"))}</div>`;
    return;
  }
  $("dupList").innerHTML = groups.map((g, gi) => {
    const rows = g.paths.map((p, i) => {
      const tag = i === 0 ? `<span class="keep">${t("dups.keep")}</span>` : "";
      const box = i === 0
        ? '<span class="dim mono">-</span>'
        : `<input type="checkbox" data-path="${esc(p)}" data-size="${g.size}" data-contents="0" data-dup="1">`;
      return `<div class="row" data-rowpath="${esc(p)}">
          ${box}
          <div class="path" title="${esc(p)}">${esc(p)} ${tag}</div>
          <div class="size">${fmt(g.size)}</div>
        </div>`;
    }).join("");
    return `<div class="dupgroup">
        <header>
          <span>${t("dups.copies", { n: g.paths.length })} · ${t("dups.each", { size: fmt(g.size) })} · ${t("dups.match")} ${t("dups." + g.confidence)}</span>
          <span class="accent mono">${t("dups.waste")} ${fmt(g.waste)}</span>
        </header>${rows}</div>`;
  }).join("");
  bindRows($("dupList"));
}

function renderOld(r) {
  fillList($("oldList"), r.old_files || [],
    (f, max) => rowHTML(f.path, f.size, max, { sub: t("files.lastmod") + " " + fmtDate(f.mtime) }),
    t("old.empty"));
}

/* ---------------------------------------------------------------- help */

const HELP = {
  en: `
    <h4>What it does</h4>
    <p>DiskLens scans a drive and answers four questions: where the space went, which caches can be cleared, which files are true duplicates, and which large files you stopped using.</p>
    <h4>Risk levels</h4>
    <ul>
      <li><b>Safe</b> means the system or the application rebuilds it automatically. Nothing breaks.</li>
      <li><b>Careful</b> means it is also rebuilt, but it costs time or a download. Example: downloaded packages, market data history.</li>
      <li><b>Info</b> means DiskLens refuses to touch it. Deleting these by hand can break your system, so the interface shows the correct command instead.</li>
    </ul>
    <h4>How deletion works</h4>
    <p>Nothing is deleted unless you tick it and confirm. The default sends items to the Recycle Bin, which means the space is only freed after you empty it. Permanent delete is disabled unless you start the tool with <code>--allow-permanent</code>.</p>
    <p>Protected locations are rejected by the server even if you try: Windows system folders, Program Files, your user folders, the paging and hibernation files.</p>
    <h4>Duplicates</h4>
    <p>Files are grouped by size, then by a hash of the first and last 64 KB, then by a full content hash. Only files that are byte for byte identical are reported as exact. Files above 2 GB are matched by sampling and marked as such.</p>
    <h4>Privacy</h4>
    <p>The tool runs only on your machine. It listens on 127.0.0.1, requires a session token for every request, and never sends anything anywhere.</p>`,
  pt: `
    <h4>O que faz</h4>
    <p>O DiskLens varre uma unidade e responde quatro perguntas: para onde o espaço foi, quais caches podem ser limpos, quais arquivos são duplicados de verdade e quais arquivos grandes você parou de usar.</p>
    <h4>Níveis de risco</h4>
    <ul>
      <li><b>Seguro</b> quer dizer que o sistema ou o programa recria sozinho. Nada quebra.</li>
      <li><b>Cuidado</b> também é recriável, mas custa tempo ou download. Exemplo: pacotes baixados, histórico de dados de mercado.</li>
      <li><b>Info</b> quer dizer que o DiskLens se recusa a mexer. Apagar isso na mão pode quebrar o sistema, então a interface mostra o comando correto.</li>
    </ul>
    <h4>Como funciona a exclusão</h4>
    <p>Nada é apagado sem você marcar e confirmar. O padrão envia para a lixeira, o que significa que o espaço só é liberado depois que você esvaziá-la. A exclusão permanente fica desativada, a menos que você inicie a ferramenta com <code>--allow-permanent</code>.</p>
    <p>Locais protegidos são recusados pelo servidor mesmo que você tente: pastas de sistema do Windows, Program Files, suas pastas pessoais, arquivos de paginação e hibernação.</p>
    <h4>Duplicados</h4>
    <p>Os arquivos são agrupados por tamanho, depois por um hash dos primeiros e últimos 64 KB, e por fim por um hash do conteúdo inteiro. Só o que é idêntico byte a byte aparece como exato. Acima de 2 GB a comparação é por amostragem e vem marcada como tal.</p>
    <h4>Privacidade</h4>
    <p>A ferramenta roda apenas na sua máquina. Escuta em 127.0.0.1, exige um token de sessão em toda requisição e não envia nada para lugar nenhum.</p>`,
};

function renderHelp() {
  $("helpBody").innerHTML = HELP[LANG] || HELP.en;
}

/* --------------------------------------------------------------- polling */

function phaseLabel(s) {
  if (s.phase === "Aggregating folders") return t("status.aggregating");
  if (s.phase === "Measuring known cleanup targets") return t("status.measuring");
  if (s.status === "hashing") return t("status.hashing");
  return t("status.scanning");
}

function setProgress(s) {
  const running = s.status === "scanning" || s.status === "hashing";
  $("progress").hidden = !running;
  $("scanBtn").disabled = running;
  $("cancelBtn").hidden = !running;
  if (!running) return;

  const bar = document.querySelector(".bar");
  if (s.status === "hashing" && s.dup_total) {
    bar.classList.remove("indeterminate");
    $("progressFill").style.width = Math.round((s.dup_done / s.dup_total) * 100) + "%";
  } else {
    bar.classList.add("indeterminate");
  }
  $("progressPhase").textContent = phaseLabel(s);
  $("progressStats").textContent = t("stats.line", {
    files: num(s.files), size: fmt(s.bytes), dirs: num(s.dirs), sec: Math.round(s.elapsed || 0),
  });
  $("progressPath").textContent = s.current || "";
}

let lastStatus = "";
async function poll() {
  try {
    const s = await api("/api/status");
    if (s.error) return;
    setProgress(s);
    if (s.status !== lastStatus) {
      if (s.status === "done") {
        const r = await api("/api/results");
        render(r);
        const total = (r.junk_safe_total || 0) + (r.junk_careful_total || 0) +
                      (r.dup_waste || 0) + (r.project_junk_total || 0);
        toast(t("toast.done", { size: fmt(total) }));
      } else if (s.status === "error") {
        toast(t("toast.error", { msg: esc(s.message) }));
      } else if (s.status === "cancelled") {
        toast(t("toast.cancelled"));
      }
      lastStatus = s.status;
    }
  } catch (e) { /* server stopped, ignore */ }
}

/* ---------------------------------------------------------------- actions */

function confirmDelete(mode) {
  const paths = [...state.selection.keys()];
  const contents = paths.filter((p) => state.selection.get(p).contentsOnly);
  let total = 0;
  state.selection.forEach((v) => { total += v.size || 0; });

  $("modalTitle").textContent = mode === "trash" ? t("modal.trashtitle") : t("modal.permtitle");
  $("modalText").innerHTML = mode === "trash"
    ? t("modal.trashtext", { n: paths.length, size: fmt(total) })
    : t("modal.permtext", { n: paths.length, size: fmt(total) });
  $("modalList").innerHTML = paths
    .map((p) => esc(p) + (state.selection.get(p).contentsOnly ? "  " + t("modal.contents") : ""))
    .join("<br>");
  $("modal").hidden = false;

  $("modalOk").onclick = async () => {
    $("modal").hidden = true;
    const res = await api("/api/delete", { paths, mode, contents_only: contents });
    if (res.error) { toast(errText(res.error)); return; }

    let msg = t("toast.freed", { size: fmt(res.freed || 0), n: (res.deleted || []).length });
    const fails = res.failed || [];
    if (fails.length) {
      const list = fails.slice(0, 3).map((f) => esc(f.path) + " (" + errText(f.error) + ")").join(" | ");
      msg += "<br><span class='dim'>" + t("toast.failed", { n: fails.length, list }) + "</span>";
    } else if (mode === "trash") {
      msg += "<br><span class='dim'>" + t("toast.trashnote") + "</span>";
    }
    toast(msg);

    (res.deleted || []).forEach((p) => {
      document.querySelectorAll(`[data-rowpath="${CSS.escape(p)}"]`).forEach((el) => el.remove());
      state.selection.delete(p);
    });
    renderActionBar();
    refreshDisk();
  };
}

async function refreshDisk() {
  const info = await api("/api/info");
  const root = state.results ? state.results.root : "";
  const hit = (info.drives || []).find((x) => root.toUpperCase().startsWith(x.path.toUpperCase()));
  if (hit && state.results) {
    state.results.disk = { total: hit.total, used: hit.used, free: hit.free };
    $("freeVal").textContent = fmt(hit.free);
    $("usedVal").textContent = fmt(hit.used);
  }
}

function setAdminFlag(admin) {
  const flag = $("adminFlag");
  flag.textContent = admin ? t("admin.yes") : t("admin.no");
  flag.className = "flag " + (admin ? "admin" : "noadmin");
}

/* ------------------------------------------------------------------- init */

async function init() {
  LANG = detectLang();
  applyI18n();

  const info = await api("/api/info");
  state.info = info;

  const sel = $("driveSelect");
  sel.innerHTML = (info.drives || [])
    .map((x) => `<option value="${esc(x.path)}">${esc(x.path)}  ${fmt(x.free)} / ${fmt(x.total)}</option>`)
    .join("");
  $("pathInput").value = info.default || "";
  sel.value = info.default;
  sel.addEventListener("change", () => { $("pathInput").value = sel.value; });
  $("minDup").value = info.min_dup_mb || 5;
  setAdminFlag(info.admin);

  if (!info.windows) $("recycleBtn").hidden = true;
  if (!info.allow_permanent) {
    $("delPerm").disabled = true;
    $("delPerm").title = t("bar.permoff");
  }

  $("scanBtn").addEventListener("click", async () => {
    clearSelection();
    lastStatus = "";
    const res = await api("/api/scan", {
      path: $("pathInput").value.trim(),
      min_dup_mb: Number($("minDup").value) || 5,
    });
    if (res.error) toast(errText(res.error) + (res.detail ? ": " + esc(res.detail) : ""));
  });

  $("cancelBtn").addEventListener("click", () => api("/api/cancel", {}));

  $("recycleBtn").addEventListener("click", async () => {
    const res = await api("/api/empty-recycle", {});
    toast(res.error ? t("toast.binerror", { msg: esc(res.error) }) : t("toast.binempty"));
    refreshDisk();
  });

  $("helpBtn").addEventListener("click", () => { $("help").hidden = false; });
  $("helpClose").addEventListener("click", () => {
    $("help").hidden = true;
    try { localStorage.setItem("disklens_help_seen", "1"); } catch (e) { /* ignore */ }
  });

  $("langBtn").addEventListener("click", () => {
    LANG = LANG === "pt" ? "en" : "pt";
    try { localStorage.setItem("disklens_lang", LANG); } catch (e) { /* ignore */ }
    applyI18n();
  });

  document.querySelectorAll(".tab").forEach((tb) => {
    tb.addEventListener("click", () => {
      document.querySelectorAll(".tab").forEach((x) => x.classList.remove("active"));
      document.querySelectorAll(".panel").forEach((x) => x.classList.remove("active"));
      tb.classList.add("active");
      $("tab-" + tb.dataset.tab).classList.add("active");
    });
  });

  $("dirFilter").addEventListener("input", () => state.results && renderDirs());
  $("dirDepth").addEventListener("change", () => state.results && renderDirs());
  $("fileFilter").addEventListener("input", () => state.results && renderFiles());

  $("selectDups").addEventListener("click", () => {
    document.querySelectorAll("#dupList input[type=checkbox][data-dup]").forEach((cb) => {
      if (!cb.checked) {
        cb.checked = true;
        cb.closest(".row").classList.add("selected");
        toggleSelect(cb.dataset.path, Number(cb.dataset.size), false, true);
      }
    });
  });

  $("clearSel").addEventListener("click", clearSelection);
  $("delTrash").addEventListener("click", () => confirmDelete("trash"));
  $("delPerm").addEventListener("click", () => confirmDelete("permanent"));
  $("modalCancel").addEventListener("click", () => { $("modal").hidden = true; });

  document.addEventListener("keydown", (e) => {
    if (e.key === "Escape") { $("modal").hidden = true; $("help").hidden = true; }
  });

  let seen = null;
  try { seen = localStorage.getItem("disklens_help_seen"); } catch (e) { /* ignore */ }
  if (!seen) $("help").hidden = false;

  setInterval(poll, 900);
  poll();
}

init();
